In [7]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv("Olympic Games medal Dataset(from 1896 to 2018).csv")
df.head()

,Team(IOC Code),summer_rank,s_gold,s_silver,s_bronze,summer_total,winter_rank,w_gold,w_silver,w_bronze,winter_total,overall_rank,total_gold,total_silver,total_bronze,total_medals
0,Afghanistan (AFG),14,0,0,2,2,0,0,0,0,0,14,0,0,2,2
1,Algeria (ALG),13,5,4,8,17,3,0,0,0,0,16,5,4,8,17
2,Argentina (ARG),24,21,25,28,74,19,0,0,0,0,43,21,25,28,74
3,Armenia (ARM),6,2,6,6,14,7,0,0,0,0,13,2,6,6,14
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Team(IOC Code)  152 non-null    object
 1   summer_rank     152 non-null    int64
 2   s_gold          152 non-null    object
 3   s_silver        152 non-null    int64
 4   s_bronze        152 non-null    int64
 5   summer_total    152 non-null    object
 6   winter_rank     152 non-null    int64
 7   w_gold          152 non-null    int64
 8   w_silver        152 non-null    int64
 9   w_bronze        152 non-null    int64
 10  winter_total    152 non-null    int64
 11  overall_rank    152 non-null    int64
 12  total_gold      152 non-null    object
 13  total_silver    152 non-null    int64
 14  total_bronze    152 non-null    int64
 15  total_medals    152 non-null    object
dtypes: int64(11), object(5)
memory usage: 19.1+ KB

In [12]:
df.describe()

,summer_rank,s_silver,s_bronze,winter_rank,w_gold,w_silver,w_bronze,winter_total,overall_rank,total_silver,total_bronze
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,13.953947,33.421053,36.098684,6.901316,6.986842,6.967105,6.907895,20.861842,20.855263,40.388158,43.006579
std,7.263570,83.156640,80.130585,7.632937,20.570018,20.013710,18.638192,58.743358,13.579010,97.470597,93.548691
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,9.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,1.000000,1.000000
50%,14.000000,4.000000,6.000000,4.500000,0.000000,0.000000,0.000000,0.000000,16.000000,4.000000,6.000000
75%,18.250000,27.750000,29.500000,10.250000,1.000000,2.000000,1.000000,4.500000,27.250000,31.000000,32.500000
max,28.000000,795.000000,706.000000,23.000000,132.000000,125.000000,111.000000,368.000000,51.000000,907.000000,794.000000

In [13]:
df.isnull().sum()

Team(IOC Code)    0
summer_rank       0
s_gold            0
s_silver          0
s_bronze          0
summer_total      0
winter_rank       0
w_gold            0
w_silver          0
w_bronze          0
winter_total      0
overall_rank      0
total_gold        0
total_silver      0
total_bronze      0
total_medals      0
dtype: int64

In [14]:
df.dtypes

Team(IOC Code)    object
summer_rank        int64
s_gold            object
s_silver           int64
s_bronze           int64
summer_total      object
winter_rank        int64
w_gold             int64
w_silver           int64
w_bronze           int64
winter_total       int64
overall_rank       int64
total_gold        object
total_silver       int64
total_bronze       int64
total_medals      object
dtype: object

In [18]:
df.shape

(152, 16)

In [27]:
df2 = pd.get_dummies(df)
df2

,summer_rank,s_silver,s_bronze,winter_rank,w_gold,w_silver,w_bronze,winter_total,overall_rank,total_silver,...,total_medals_8,total_medals_840,total_medals_855,total_medals_86,total_medals_87,total_medals_883,total_medals_9,total_medals_91,total_medals_94,total_medals_96
0,14,0,2,0,0,0,0,0,14,0,...,0,0,0,0,0,0,0,0,0,0
1,13,4,8,3,0,0,0,0,16,4,...,0,0,0,0,0,0,0,0,0,0
2,24,25,28,19,0,0,0,0,43,25,...,0,0,0,0,0,0,0,0,0,0
3,6,6,6,7,0,0,0,0,13,6,...,0,0,0,0,0,0,0,0,0,0
4,2,4,5,0,0,0,0,0,2,4,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,13,1,1,0,0,0,0,0,13,1,...,0,0,0,0,0,0,0,0,0,0
148,13,4,1,1,0,0,0,0,14,4,...,1,0,0,0,0,0,0,0,0,0
149,3,0,1,0,0,0,0,0,3,0,...,0,0,0,0,0,0,0,0,0,0
150,1,1,2,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
151,3,5,4,0,0,0,0,0,3,5,...,0,0,0,0,0,0,0,0,0,0

In [37]:
df2.describe()

,summer_rank,s_silver,s_bronze,winter_rank,w_gold,w_silver,w_bronze,winter_total,overall_rank,total_silver,...,total_medals_8,total_medals_840,total_medals_855,total_medals_86,total_medals_87,total_medals_883,total_medals_9,total_medals_91,total_medals_94,total_medals_96
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,...,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,13.953947,33.421053,36.098684,6.901316,6.986842,6.967105,6.907895,20.861842,20.855263,40.388158,...,0.013158,0.006579,0.006579,0.006579,0.006579,0.006579,0.013158,0.006579,0.006579,0.006579
std,7.263570,83.156640,80.130585,7.632937,20.570018,20.013710,18.638192,58.743358,13.579010,97.470597,...,0.114327,0.081111,0.081111,0.081111,0.081111,0.081111,0.114327,0.081111,0.081111,0.081111
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,14.000000,4.000000,6.000000,4.500000,0.000000,0.000000,0.000000,0.000000,16.000000,4.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,18.250000,27.750000,29.500000,10.250000,1.000000,2.000000,1.000000,4.500000,27.250000,31.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,28.000000,795.000000,706.000000,23.000000,132.000000,125.000000,111.000000,368.000000,51.000000,907.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [33]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Columns: 420 entries, summer_rank to total_medals_96
dtypes: int64(11), uint8(409)
memory usage: 73.9 KB

In [28]:
df.corr()

,summer_rank,s_silver,s_bronze,winter_rank,w_gold,w_silver,w_bronze,winter_total,overall_rank,total_silver,total_bronze
summer_rank,1.000000,0.358495,0.389962,0.661663,0.313942,0.325806,0.366120,0.337097,0.906841,0.372747,0.406972
s_silver,0.358495,1.000000,0.989499,0.519493,0.654805,0.656425,0.644621,0.657460,0.483777,0.987930,0.976002
s_bronze,0.389962,0.989499,1.000000,0.565164,0.669064,0.669976,0.663903,0.673188,0.526281,0.981753,0.988838
winter_rank,0.661663,0.519493,0.565164,1.000000,0.502302,0.519849,0.569625,0.533733,0.916044,0.549944,0.597589
w_gold,0.313942,0.654805,0.669064,0.502302,1.000000,0.982866,0.966061,0.991541,0.450282,0.760456,0.765570
w_silver,0.325806,0.656425,0.669976,0.519849,0.982866,1.000000,0.978120,0.995205,0.466491,0.765357,0.768754
w_bronze,0.366120,0.644621,0.663903,0.569625,0.966061,0.978120,1.000000,0.988808,0.516035,0.750794,0.767912
winter_total,0.337097,0.657460,0.673188,0.533733,0.991541,0.995205,0.988808,1.000000,0.480335,0.765256,0.773635
overall_rank,0.906841,0.483777,0.526281,0.916044,0.450282,0.466491,0.516035,0.480335,1.000000,0.508517,0.553607
total_silver,0.372747,0.987930,0.981753,0.549944,0.760456,0.765357,0.750794,0.765256,0.508517,1.000000,0.990521
total_bronze,0.406972,0.976002,0.988838,0.597589,0.765570,0.768754,0.767912,0.773635,0.553607,0.990521,1.000000

In [38]:
X = df2.drop(['summer_rank'],axis = 1)
y = df2['summer_rank']

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20)

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train,y_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [41]:
from sklearn.tree import DecisionTreeRegressor
regressordt = DecisionTreeRegressor(random_state=0)
regressordt.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

In [42]:
y_preddt = regressordt.predict(X_test)
y_preddt

array([14.,  9., 13., 12.,  9., 21., 10., 23., 14.,  9., 12., 21.,  7.,
        7.,  6.,  9., 28.,  9.,  9., 16., 14., 12.,  9.,  9., 13., 17.,
        9.,  5., 17., 22., 16.])

In [43]:
regressordt.score(X_test,y_test)

0.6500141123341802

In [44]:
from sklearn.linear_model import LinearRegression
regressorlin = LinearRegression()
regressorlin.fit(X_train,y_train)

LinearRegression()

In [45]:
y_predlin = regressorlin.predict(X_test)

In [46]:
regressorlin.score(X_test,y_test)

0.1666843132832707

In [56]:
from sklearn.ensemble import RandomForestRegressor
regressorrfr = RandomForestRegressor(n_estimators=100, criterion='mse')
regressorrfr.fit(X_train,y_train)

RandomForestRegressor()

In [57]:
y_predrfr = regressorrfr.predict(X_test)

In [58]:
regressorrfr.score(X_test,y_test)

0.8788480101608805

In [62]:
from sklearn.svm import SVR
regressorsvr = SVR(kernel = 'rbf', C=1.0)
regressorsvr.fit(X_train,y_train)

SVR()

In [63]:
y_predsvr = regressorsvr.predict(X_test)

In [64]:
regressorsvr.score(X_test,y_test)

0.13599561706715602

In [67]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(regressorrfr,X_train,y_train,cv=5)
scores,scores.mean

(array([0.9152743 , 0.9515174 , 0.96998043, 0.95162068, 0.89679768]),
 <function ndarray.mean>)