In [5]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('WorldPopulation.csv')
df.head()

   Year  Population  ChangePerc  NetChange  Density       Urban  UrbanPerc
0  2020  7794798739        1.05   81330639       52  4378993944         56
1  2019  7713468100        1.08   82377060       52  4299438618         56
2  2018  7631091040        1.10   83232115       51  4219817318         55
3  2017  7547858925        1.12   83836876       51  4140188594         55
4  2016  7464022049        1.14   84224910       50  4060652683         54

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        70 non-null     int64
 1   Population  70 non-null     int64
 2   ChangePerc  70 non-null     float64
 3   NetChange   70 non-null     int64
 4   Density     70 non-null     int64
 5   Urban       70 non-null     int64
 6   UrbanPerc   70 non-null     int64
dtypes: float64(1), int64(6)
memory usage: 4.0 KB

In [8]:
df.describe()

,Year,Population,ChangePerc,NetChange,Density,Urban,UrbanPerc
count,70.000000,7.000000e+01,70.000000,7.000000e+01,70.000000,7.000000e+01,70.000000
mean,1985.500000,5.002010e+09,1.616429,7.511954e+07,33.557143,2.226815e+09,42.200000
std,20.351085,1.594877e+09,0.321288,1.256972e+07,10.723989,1.070191e+09,7.447595
min,1951.000000,2.584034e+09,1.050000,4.674740e+07,17.000000,7.750677e+08,30.000000
25%,1968.250000,3.570120e+09,1.262500,7.314225e+07,24.000000,1.294408e+09,36.000000
50%,1985.500000,4.915745e+09,1.770000,7.942852e+07,33.000000,2.035272e+09,41.500000
75%,2002.750000,6.361332e+09,1.847500,8.356683e+07,42.750000,3.054260e+09,48.000000
max,2020.000000,7.794799e+09,2.090000,9.290386e+07,52.000000,4.378994e+09,56.000000

In [9]:
df.isnull().sum()

Year          0
Population    0
ChangePerc    0
NetChange     0
Density       0
Urban         0
UrbanPerc     0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        70 non-null     int64
 1   Population  70 non-null     int64
 2   ChangePerc  70 non-null     float64
 3   NetChange   70 non-null     int64
 4   Density     70 non-null     int64
 5   Urban       70 non-null     int64
 6   UrbanPerc   70 non-null     int64
dtypes: float64(1), int64(6)
memory usage: 4.0 KB

In [11]:
X = df.drop('UrbanPerc',axis=1)
y = df['UrbanPerc']

In [12]:
y

0     56
1     56
2     55
3     55
4     54
      ..
65    32
66    31
67    31
68    30
69    30
Name: UrbanPerc, Length: 70, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5)

In [14]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train,y_train)

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

DecisionTreeRegressor(random_state=0)

In [15]:
y_pred = regressor.predict(X_test)
y_pred

array([36., 39., 36., 46., 56., 44., 49., 54., 41., 41., 37., 46., 56.,
       39., 49., 38., 52., 48., 51., 36., 44., 38., 46., 54., 37., 33.,
       31., 36., 44., 43., 36., 48., 53., 40., 32.])

In [16]:
regressor.score(X_test,y_test)

0.9910822345372317

In [17]:
from sklearn.linear_model import LinearRegression
regressorlin = LinearRegression()
regressorlin.fit(X_train,y_train)

LinearRegression()

In [18]:
y_predlin = regressorlin.predict(X_test)
y_predlin

array([36.81587075, 39.70947083, 35.48137027, 45.48860028, 55.49494638,
       43.18884342, 49.54182257, 54.98888481, 41.56040888, 41.85469054,
       37.11477742, 45.10652166, 56.53907367, 39.03714532, 50.04238118,
       38.68923646, 52.01107741, 47.14516598, 50.53130744, 36.54995088,
       44.33214708, 38.04031478, 46.69372869, 53.96980052, 37.40458076,
       32.90629226, 30.53794164, 34.98111721, 44.72092736, 42.82652577,
       35.72849618, 48.58062676, 52.97282393, 40.04797547, 32.16469873])

In [19]:
regressorlin.score(X_test,y_test)

0.9977336896485112

In [20]:
from sklearn.linear_model import LogisticRegression
regressorlog = LogisticRegression()
regressorlog.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [21]:
y_predlog = regressorlog.predict(X_test)
y_predlog

array([36, 39, 36, 46, 56, 44, 49, 54, 41, 41, 36, 44, 56, 39, 49, 38, 52,
       46, 49, 36, 44, 37, 46, 53, 36, 34, 31, 36, 44, 41, 36, 48, 53, 40,
       32], dtype=int64)

In [22]:
regressorlog.score(X_test,y_test)

0.34285714285714286

In [23]:
from sklearn.ensemble import RandomForestRegressor
regressorrf = RandomForestRegressor()
regressorrf.fit(X_train,y_train)

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

RandomForestRegressor()

In [24]:
y_predrf = regressorrf.predict(X_test)
y_predrf

array([36.45, 39.3 , 35.87, 46.01, 54.62, 43.53, 48.71, 54.01, 41.08,
       41.64, 36.96, 45.58, 54.67, 38.37, 49.94, 38.05, 52.35, 47.59,
       51.07, 36.35, 44.38, 37.31, 46.5 , 53.45, 37.05, 32.61, 30.82,
       35.38, 44.68, 42.95, 35.94, 48.06, 52.86, 39.77, 31.82])

In [25]:
regressorrf.score(X_test,y_test)

0.9938109035607363

In [26]:
from sklearn.svm import SVR
regressorsvr = SVR(kernel = 'rbf')
regressorsvr.fit(X_train,y_train)

SVR()

In [27]:
y_predsvr = regressorsvr.predict(X_test)
y_predsvr

array([36.96708838, 39.40918319, 35.90373183, 45.31005903, 49.40678408,
       43.35032144, 47.74692481, 49.36010886, 41.47122231, 41.8530671 ,
       37.20838183, 45.00289532, 49.45157936, 38.80265672, 47.97038659,
       38.51886262, 48.7250781 , 46.46420984, 48.18174632, 36.73564976,
       44.36544255, 37.97936184, 46.18363903, 49.21613986, 37.45903243,
       34.75822718, 34.24212088, 35.56014586, 44.68785089, 42.99036369,
       36.09511209, 47.26351675, 49.00405518, 39.72956991, 34.55980167])

In [28]:
regressorsvr.score(X_test,y_test)

0.8848291392233087

In [41]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(regressorlin,X_train,y_train,cv=5)
scores,scores.mean()

(array([0.99293311, 0.99721332, 0.99681474, 0.99560986, 0.99764567]),
 0.9960433391098498)